/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/lib/python3.9/site-packages/torchvision/transforms/_functional_video.py:6: UserWarning: The 'torchvision.transforms._functional_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms.functional' module instead.
  warnings.warn(
/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/lib/python3.9/site-packages/torchvision/transforms/_functional_video.py:6: UserWarning: The 'torchvision.transforms._functional_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms.functional' module instead.
  warnings.warn(
/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/lib/python3.9/site-packages/torchvision/transforms/_functional_video.py:6: UserWarning: The 'torchvision.transforms._functional_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms.functional' module instead.
  warnings.warn(
/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/lib/python3.9/site-packages/torchvision/transforms/_functional_video.py:6: UserWarning: The 'torchvision.transforms._functional_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms.functional' module instead.
  warnings.warn(
/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/lib/python3.9/site-packages/torchvision/transforms/_functional_video.py:6: UserWarning: The 'torchvision.transforms._functional_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms.functional' module instead.
  warnings.warn(
/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/lib/python3.9/site-packages/torchvision/transforms/_functional_video.py:6: UserWarning: The 'torchvision.transforms._functional_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms.functional' module instead.
  warnings.warn(
/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/lib/python3.9/site-packages/torchvision/transforms/_transforms_video.py:22: UserWarning: The 'torchvision.transforms._transforms_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms' module instead.
  warnings.warn(
/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/lib/python3.9/site-packages/torchvision/transforms/_transforms_video.py:22: UserWarning: The 'torchvision.transforms._transforms_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms' module instead.
  warnings.warn(
/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/lib/python3.9/site-packages/torchvision/transforms/_transforms_video.py:22: UserWarning: The 'torchvision.transforms._transforms_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms' module instead.
  warnings.warn(
/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/lib/python3.9/site-packages/torchvision/transforms/_transforms_video.py:22: UserWarning: The 'torchvision.transforms._transforms_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms' module instead.
  warnings.warn(
/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/lib/python3.9/site-packages/torchvision/transforms/_transforms_video.py:22: UserWarning: The 'torchvision.transforms._transforms_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms' module instead.
  warnings.warn(
/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/lib/python3.9/site-packages/torchvision/transforms/_transforms_video.py:22: UserWarning: The 'torchvision.transforms._transforms_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms' module instead.
  warnings.warn(
/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/lib/python3.9/site-packages/torchvision/transforms/_functional_video.py:6: UserWarning: The 'torchvision.transforms._functional_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms.functional' module instead.
  warnings.warn(
/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/lib/python3.9/site-packages/torchvision/transforms/_functional_video.py:6: UserWarning: The 'torchvision.transforms._functional_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms.functional' module instead.
  warnings.warn(
/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/lib/python3.9/site-packages/torchvision/transforms/_transforms_video.py:22: UserWarning: The 'torchvision.transforms._transforms_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms' module instead.
  warnings.warn(
/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/lib/python3.9/site-packages/torchvision/transforms/_transforms_video.py:22: UserWarning: The 'torchvision.transforms._transforms_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms' module instead.
  warnings.warn(
Traceback (most recent call last):
  File "/scratch/user/hasnat.md.abdullah/uag/foundation_models/Video-LLaMA/train.py", line 107, in <module>
Traceback (most recent call last):
  File "/scratch/user/hasnat.md.abdullah/uag/foundation_models/Video-LLaMA/train.py", line 107, in <module>
Traceback (most recent call last):
  File "/scratch/user/hasnat.md.abdullah/uag/foundation_models/Video-LLaMA/train.py", line 107, in <module>
Traceback (most recent call last):
  File "/scratch/user/hasnat.md.abdullah/uag/foundation_models/Video-LLaMA/train.py", line 107, in <module>
Traceback (most recent call last):
  File "/scratch/user/hasnat.md.abdullah/uag/foundation_models/Video-LLaMA/train.py", line 107, in <module>
Traceback (most recent call last):
  File "/scratch/user/hasnat.md.abdullah/uag/foundation_models/Video-LLaMA/train.py", line 107, in <module>
Traceback (most recent call last):
  File "/scratch/user/hasnat.md.abdullah/uag/foundation_models/Video-LLaMA/train.py", line 107, in <module>
    main()
  File "/scratch/user/hasnat.md.abdullah/uag/foundation_models/Video-LLaMA/train.py", line 84, in main
    init_distributed_mode(cfg.run_cfg)
  File "/scratch/user/hasnat.md.abdullah/uag/foundation_models/Video-LLaMA/video_llama/common/dist_utils.py", line 72, in init_distributed_mode
    main()
  File "/scratch/user/hasnat.md.abdullah/uag/foundation_models/Video-LLaMA/train.py", line 84, in main
    init_distributed_mode(cfg.run_cfg)
  File "/scratch/user/hasnat.md.abdullah/uag/foundation_models/Video-LLaMA/video_llama/common/dist_utils.py", line 72, in init_distributed_mode
    main()
  File "/scratch/user/hasnat.md.abdullah/uag/foundation_models/Video-LLaMA/train.py", line 84, in main
    init_distributed_mode(cfg.run_cfg)
  File "/scratch/user/hasnat.md.abdullah/uag/foundation_models/Video-LLaMA/video_llama/common/dist_utils.py", line 72, in init_distributed_mode
    main()
  File "/scratch/user/hasnat.md.abdullah/uag/foundation_models/Video-LLaMA/train.py", line 84, in main
    init_distributed_mode(cfg.run_cfg)
  File "/scratch/user/hasnat.md.abdullah/uag/foundation_models/Video-LLaMA/video_llama/common/dist_utils.py", line 72, in init_distributed_mode
    main()
  File "/scratch/user/hasnat.md.abdullah/uag/foundation_models/Video-LLaMA/train.py", line 84, in main
    init_distributed_mode(cfg.run_cfg)
  File "/scratch/user/hasnat.md.abdullah/uag/foundation_models/Video-LLaMA/video_llama/common/dist_utils.py", line 72, in init_distributed_mode
    main()
  File "/scratch/user/hasnat.md.abdullah/uag/foundation_models/Video-LLaMA/train.py", line 84, in main
    init_distributed_mode(cfg.run_cfg)
  File "/scratch/user/hasnat.md.abdullah/uag/foundation_models/Video-LLaMA/video_llama/common/dist_utils.py", line 72, in init_distributed_mode
    main()
  File "/scratch/user/hasnat.md.abdullah/uag/foundation_models/Video-LLaMA/train.py", line 84, in main
    init_distributed_mode(cfg.run_cfg)
  File "/scratch/user/hasnat.md.abdullah/uag/foundation_models/Video-LLaMA/video_llama/common/dist_utils.py", line 72, in init_distributed_mode
    torch.cuda.set_device(args.gpu)
  File "/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/lib/python3.9/site-packages/torch/cuda/__init__.py", line 399, in set_device
    torch.cuda.set_device(args.gpu)
  File "/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/lib/python3.9/site-packages/torch/cuda/__init__.py", line 399, in set_device
    torch.cuda.set_device(args.gpu)
  File "/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/lib/python3.9/site-packages/torch/cuda/__init__.py", line 399, in set_device
    torch.cuda.set_device(args.gpu)
  File "/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/lib/python3.9/site-packages/torch/cuda/__init__.py", line 399, in set_device
    torch.cuda.set_device(args.gpu)
  File "/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/lib/python3.9/site-packages/torch/cuda/__init__.py", line 399, in set_device
    torch.cuda.set_device(args.gpu)
  File "/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/lib/python3.9/site-packages/torch/cuda/__init__.py", line 399, in set_device
    torch.cuda.set_device(args.gpu)
  File "/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/lib/python3.9/site-packages/torch/cuda/__init__.py", line 399, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

W0614 09:36:29.809592 47176860399744 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 158903 closing signal SIGTERM
E0614 09:36:30.078333 47176860399744 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 1 (pid: 158904) of binary: /scratch/user/hasnat.md.abdullah/.conda/envs/videollama/bin/python
Traceback (most recent call last):
  File "/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/lib/python3.9/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/lib/python3.9/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/scratch/user/hasnat.md.abdullah/.conda/envs/videollama/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-06-14_09:36:29
  host      : g075.cluster
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 158905)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-06-14_09:36:29
  host      : g075.cluster
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 158906)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-06-14_09:36:29
  host      : g075.cluster
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 158907)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2024-06-14_09:36:29
  host      : g075.cluster
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 158908)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2024-06-14_09:36:29
  host      : g075.cluster
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 158909)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2024-06-14_09:36:29
  host      : g075.cluster
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 158910)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-06-14_09:36:29
  host      : g075.cluster
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 158904)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
